In [ ]:

                                                                                                             Рабочая тетрадь № 2
Цель машинного обучения – анализ данных. 
Данные – зарегистрированная информация; представление фактов, 
понятий или инструкций в форме, приемлемой для общения, 
интерпретации, или обработки человеком или с помощью автоматических 
средств (ISO/IEC/IEEE 24765-2010).


In [ ]:
NumPy (NumericalPython) - это библиотека Python с открытым 
исходным кодом, которая используется практически во всех областях науки 
и техники. Это универсальный стандарт для работы с числовыми данными в 
Python.
Если у вас уже есть Python, вы можете установить NumPy с помощью 
командной строки:
----- pip install numpy
Чтобы начать использовать NumPy необходимо импортировать 
соответствующую библиотеку:
 import numpy as np
Основным объектом NumPy является однородный многомерный 
массив (в numpy называется numpy.ndarray). Это многомерный массив 
элементов (обычно чисел), одного типа.
Наиболее важные атрибуты объектов ndarray:

ndarray.ndim - число измерений (чаще их называют "оси") массива.

ndarray.shape - размеры массива, его форма. Это кортеж натуральных 

чисел, показывающий длину массива по каждой оси. Для матрицы из n строк 
и m столбов, shape будет (n,m). Число элементов кортежа shape равно ndim.
ndarray.size - количество элементов массива. Очевидно, равно 
произведению всех элементов атрибута shape.

ndarray.dtype - объект, описывающий тип элементов массива. Можно 
определить dtype, используя стандартные типы данных Python. NumPy здесь 
предоставляет целый букет возможностей, как встроенных, например: bool_, 
character, int8, int16, int32, int64, float8, float16, float32, float64, complex64, 
object_, так и возможность определить собственные типы данных, в том 
числе и составные.

ndarray.itemsize - размер каждого элемента массива в байтах.
ndarray.data - буфер, содержащий фактические элементы массива. 
Обычно не нужно использовать этот атрибут, так как обращаться к 
элементам массива проще всего с помощью индексов.
Подробнее о массивах в NumPy можно найти в официальной 
документации https://numpy.org/doc/stable/user/absolute_beginners.html


In [ ]:
1.2.1 Пример
Задача:
Создать массив 5x2. Создать массив 5x2. Вывести все значения массива, 
значение элемента с индексом (3,1) и второй столбец. Индексация 
начинается с нуля
-----Решение

In [ ]:
import numpy as np
x=np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
print(x)
print(x[3][1])
print(x[:,1])
print(x.shape)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[ 2  4  6  8 10]
(5, 2)


In [ ]:
    1.2.2 Пример
 Задача:
 Выполнить следующее:
1. Создать вектор (одномерный массив) размера 10, заполненный  нулями.
2. Создать вектор размера 10, заполненный единицами
3. Создать вектор размера 10, заполненный заданным числом
4. Создать вектор со значениями от 10 до 49

Решение:

In [ ]:
a=np.zeros(10)
b=np.ones(10)
c=np.full(10,5)
d=np.arange(10,20)
print(a,"\n",b,"\n",c,"\n",d ,"\n")

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19] 



In [ ]:
     1.2.3 Пример
Задача:
Создать массив 10x10 со случайными значениями, найти минимум, 
максимум и среднее значение
Решение

In [ ]:
z=np.random.random((10,10))
z_min,z_max,z_mean=z.min(),z.max(),z.mean()
print(z_min,z_max,z_mean)

0.0028294628648519726 0.9780777800281357 0.48386716055157786


In [ ]:
1.2.4 Пример
Задача:
Задать матрицу размерности 5 на 5 и поменять 2 строки в матрице
местами
Решение

In [ ]:
a=np.arange(25).reshape(5,5)
a[[0,1]]=a[[1,0]]
print(a)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
1.2.5 Пример
Задача:
Выяснить результат следующих выражений:

0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
Решение

In [ ]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(0.3==3*0.1)



nan
False
False
nan
False


In [ ]:
1.2.6 Пример
Задача:
Отсортировать массив
Решение:

In [ ]:
arr=np.array([2,3,0,7,6,555,35235,314524325])
print(np.sort(arr))

[        0         2         3         6         7       555     35235
 314524325]


In [ ]:
1.3.1 Задание
Задача:
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и 
единицами

In [ ]:
a = np.ones((8, 8))
a[1::2,::2]=0
a[::2,1::2]=0
print(a)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [ ]:
1.3.2 Задание
Задача:
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания 
необходимо использовать функцию arrange

In [ ]:
a = np.zeros((5, 5))
b=np.arange(0,5)
c=a+b
print(c)


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [ ]:
1.3.3 Задание
Задача:
Создать массив 3x3x3 со случайными значениями
Решение

In [ ]:
z=np.random.randint(100,size=(3,3))
print(z)

[[21 19 56]
 [14 58 62]
 [39 54 77]]


In [ ]:
1.3.4 Задание
Задача:
Создать матрицу с 0 внутри, и 1 на границах
Решение

In [ ]:
z=np.zeros((5,5))
z[0,::1]=1

print(z)
z[::-1,0]=1

print(z)
z[-1,::1]=1

print(z)
z[::1,-1]=1

print(z)
print(z)

[[1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
1.3.5 Задание
Задача:
Создайте массив и отсортируйте его по убыванию
Решение

In [ ]:
v=np.random.randint(400,size=10)
print(v)
v = sorted(v, reverse=True)
print(v)




[117 148 296 108  44 351 147 369 325 182]
[369, 351, 325, 296, 182, 148, 147, 117, 108, 44]


In [ ]:
1.3.6 Задание
Задача:
Создайте матрицу, выведите ее форму, размер и размерность.

In [ ]:
z=np.random.randint(100,size=(3,3))
print(z.shape)
print(z.size)
print(z.dtype)

(3, 3)
9
int64


In [ ]:
2.1. Теоретический материал – Библиотека Pandas
Первым шагом в любом начинании в области машинного обучения 
является введение исходных данных в систему. Исходные данные могут 
вводиться вручную, содержаться в файле или храниться в интернете в каком-либо формате. Кроме того, часто требуется получить данные из нескольких 
источников.
Библиотека pandas – это удобный и быстрый инструмент для работы 
с данными, обладающий большим функционалом. Если очень кратко, то
pandas – это библиотека, которая предоставляет очень удобные с точки 
зрения использования инструменты для хранения данных и работе с ними. 
Библиотека pandas присутствует в стандартной поставке Anaconda. 
Если же ее там нет, то его можно установить отдельно. Для этого введите 
командной строке:
 pip install pandas
Для импорта библиотеки используйте команду:
import pandas as pd
Библиотека pandas предоставляет две ключевые структуры данных:
Series и DataFrame.
Series – это одномерная структура данных, ее можно представить, как 
таблицу с одной строкой. С Series можно работать как с обычным массивом (обращаться по номеру индекса), и как с ассоциированным массивом, когда 
можно использовать ключ для доступа к элементам данных.
DataFrame – это двумерная структура. Идейно она очень похожа на 
обычную таблицу, что выражается в способе ее создания и работе с ее 
элементами.

In [ ]:
2.2.1 Пример
Задача:
Создать Series из списка Python, словаря Python, и массива 
Numpy (установить буквенные метки для последнего).
Решение

In [ ]:
import pandas as pd 
l=[1,2,3,4,5]
dictinary={'a':1,'b':2,'c':3}
ndarr=np.array([1,2,3,4,5])
s1=pd.Series(l)
s2=pd.Series(dictinary)
s3=pd.Series(ndarr,['a','b','c','d','e'])
print(s1)
print(s2)
print(s3)



0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64


In [ ]:
2.2.2 Пример
Задача:
Дано два Series. Напечатать их первые элементы и все 
элементы после третьего (во втором фрейме).
Решение

In [ ]:
s1=pd.Series([1,2,3,4,5],['a','b','c','d','e'])
s2=pd.Series([5,4,3,2,1])
print(s1['a'])
print(s2[0])
print(s2[1:])



1
5
1    4
2    3
3    2
4    1
dtype: int64


In [ ]:
2.2.3 Пример
Задача:
Создайте новый фрейм данных.
Решение

In [ ]:
dataframe=pd.DataFrame()
dataframe['Имя']=['Джекси Джексон','Стивен Хокинг']
dataframe['Возраст']=[38,25]
dataframe['Водитель']=[True,False]
dataframe

Имя  Возраст  Водитель
0  Джекси Джексон       38      True
1   Стивен Хокинг       25     False

In [ ]:
2.2.4 Пример
Задача:
Загрузите фрейм данных по ссылке: 
https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titan
ic.csv
Решение:


In [ ]:
#Создаем URL адрес
url='https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
#Загрузить данные
dataframe=pd.read_csv(url)
dataframe.head(5)



Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

In [ ]:
2.2.5 Пример
Задача:
Провести анализ датафрэйма.
Решение:
Одна из самых простых вещей, которые мы можем сделать 
после загрузки данных, – это взглянуть на первые несколько строк 
с помощью метода head. На последние строки можно посмотреть с 
помощью функции tail. Мы также можем взглянуть на количество 
строк и столбцов: dataframe.shape. Кроме того, используя метод 
describe, мы можем получить описательную статистику для любых 
числовых столбцов.

In [ ]:
dataframe.head(2)
dataframe.tail(2)
dataframe.shape
dataframe.describe()


Age     Survived      SexCode
count  756.000000  1313.000000  1313.000000
mean    30.397989     0.342727     0.351866
std     14.259049     0.474802     0.477734
min      0.170000     0.000000     0.000000
25%     21.000000     0.000000     0.000000
50%     28.000000     0.000000     0.000000
75%     39.000000     1.000000     1.000000
max     71.000000     1.000000     1.000000

In [ ]:
2.2.6 Пример
Задача:
Выберите индивидуальные данные или срезы фрейма данных.
Решение:
Для выбора одной или нескольких строк либо значений использовать 
методы 1ос или iloc
 Решение

In [ ]:
dataframe.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

In [ ]:
2.2.7 Пример
Задача:
Требуется отобрать строки фрейма данных на основе некоторого 
условия. Необходимо сформировать новый фрейм данных из пассажиров 
первого класса.
Решение:

In [ ]:
dataframe[dataframe['PClass']=='1st'].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

In [ ]:
2.3.1 Задание
Задача:
Найдите евклидово расстояние между двумя Series (точками) a и b, 
не используя встроенную формулу.
Решение

In [ ]:
s2=pd.Series([5,4,3,2,1])
d=np.sqrt(((s2[0]-s2[1])*(s2[0]+s2[1])))
print((d))

3.0


In [ ]:
2.3.2 Задание
Задача:
Найдите в Интернете ссылку на любой csv файл и сформируйте из него 
фрейм данных (например, коллекцию фреймов данный можно найти 
здесь: https://github.com/akmand/datasets)
Решение

In [ ]:
url= 'https://raw.githubusercontent.com/akmand/datasets/main/wine.csv'

In [ ]:
df = pd.read_csv(url,error_bad_lines=False, engine ='python')
df

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)


1     2     3     4    5     6     7     8     9     10    11    12  \
0    14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29   5.64  1.04  3.92   
1    13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28   4.38  1.05  3.40   
2    13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81   5.68  1.03  3.17   
3    14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18   7.80  0.86  3.45   
4    13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82   4.32  1.04  2.93   
..     ...   ...   ...   ...  ...   ...   ...   ...   ...    ...   ...   ...   
173  13.71  5.65  2.45  20.5   95  1.68  0.61  0.52  1.06   7.70  0.64  1.74   
174  13.40  3.91  2.48  23.0  102  1.80  0.75  0.43  1.41   7.30  0.70  1.56   
175  13.27  4.28  2.26  20.0  120  1.59  0.69  0.43  1.35  10.20  0.59  1.56   
176  13.17  2.59  2.37  20.0  120  1.65  0.68  0.53  1.46   9.30  0.60  1.62   
177  14.13  4.10  2.74  24.5   96  2.05  0.76  0.56  1.35   9.20  0.61  1.60   

       13  y  
0    1065  1  
1    1050  1  
2    1185  1  
3    1480  1  
4     735  1  
..    ... ..  
173   740  3  
174   750  3  
175   835  3  
176   840  3  
177   560  3  

[178 rows x 14 columns]

In [ ]:
2.3.3 Задание
Задача:
Проделайте с получившемся из предыдущего задания фреймом 
данных те же действия, что и в примерах 2.2.5-2.2.7
Решение:

SyntaxError: ignored

In [ ]:
df.head(2)
df.tail(2)
df.shape
df.describe()

1           2           3           4           5           6  \
count  178.000000  178.000000  178.000000  178.000000  178.000000  178.000000   
mean    13.000618    2.336348    2.366517   19.494944   99.741573    2.295112   
std      0.811827    1.117146    0.274344    3.339564   14.282484    0.625851   
min     11.030000    0.740000    1.360000   10.600000   70.000000    0.980000   
25%     12.362500    1.602500    2.210000   17.200000   88.000000    1.742500   
50%     13.050000    1.865000    2.360000   19.500000   98.000000    2.355000   
75%     13.677500    3.082500    2.557500   21.500000  107.000000    2.800000   
max     14.830000    5.800000    3.230000   30.000000  162.000000    3.880000   

                7           8           9          10          11          12  \
count  178.000000  178.000000  178.000000  178.000000  178.000000  178.000000   
mean     2.029270    0.361854    1.590899    5.058090    0.957449    2.611685   
std      0.998859    0.124453    0.572359    2.318286    0.228572    0.709990   
min      0.340000    0.130000    0.410000    1.280000    0.480000    1.270000   
25%      1.205000    0.270000    1.250000    3.220000    0.782500    1.937500   
50%      2.135000    0.340000    1.555000    4.690000    0.965000    2.780000   
75%      2.875000    0.437500    1.950000    6.200000    1.120000    3.170000   
max      5.080000    0.660000    3.580000   13.000000    1.710000    4.000000   

                13           y  
count   178.000000  178.000000  
mean    746.893258    1.938202  
std     314.907474    0.775035  
min     278.000000    1.000000  
25%     500.500000    1.000000  
50%     673.500000    2.000000  
75%     985.000000    3.000000  
max    1680.000000    3.000000

In [ ]:
Задание 2.2.6


In [ ]:
df.iloc[1:4]

1     2     3     4    5     6     7     8     9    10    11    12  \
1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   

     13  y  
1  1050  1  
2  1185  1  
3  1480  1

In [ ]:
 Задание 2.2.7

In [ ]:
df[df['y']==1].head(19)

1     2     3     4    5     6     7     8     9    10    11    12  \
0   14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   
5   14.20  1.76  2.45  15.2  112  3.27  3.39  0.34  1.97  6.75  1.05  2.85   
6   14.39  1.87  2.45  14.6   96  2.50  2.52  0.30  1.98  5.25  1.02  3.58   
7   14.06  2.15  2.61  17.6  121  2.60  2.51  0.31  1.25  5.05  1.06  3.58   
8   14.83  1.64  2.17  14.0   97  2.80  2.98  0.29  1.98  5.20  1.08  2.85   
9   13.86  1.35  2.27  16.0   98  2.98  3.15  0.22  1.85  7.22  1.01  3.55   
10  14.10  2.16  2.30  18.0  105  2.95  3.32  0.22  2.38  5.75  1.25  3.17   
11  14.12  1.48  2.32  16.8   95  2.20  2.43  0.26  1.57  5.00  1.17  2.82   
12  13.75  1.73  2.41  16.0   89  2.60  2.76  0.29  1.81  5.60  1.15  2.90   
13  14.75  1.73  2.39  11.4   91  3.10  3.69  0.43  2.81  5.40  1.25  2.73   
14  14.38  1.87  2.38  12.0  102  3.30  3.64  0.29  2.96  7.50  1.20  3.00   
15  13.63  1.81  2.70  17.2  112  2.85  2.91  0.30  1.46  7.30  1.28  2.88   
16  14.30  1.92  2.72  20.0  120  2.80  3.14  0.33  1.97  6.20  1.07  2.65   
17  13.83  1.57  2.62  20.0  115  2.95  3.40  0.40  1.72  6.60  1.13  2.57   
18  14.19  1.59  2.48  16.5  108  3.30  3.93  0.32  1.86  8.70  1.23  2.82   

      13  y  
0   1065  1  
1   1050  1  
2   1185  1  
3   1480  1  
4    735  1  
5   1450  1  
6   1290  1  
7   1295  1  
8   1045  1  
9   1045  1  
10  1510  1  
11  1280  1  
12  1320  1  
13  1150  1  
14  1547  1  
15  1310  1  
16  1280  1  
17  1130  1  
18  1680  1

In [ ]:
3.1. Теоретический материал – Работа с числовыми данными
Количественные данные что-то измеряют – будь то размер класса, 
ежемесячные продажи или оценки учащихся. Естественным способом 
представления этих величин является численным (например, 150 студентов, 
$529 392 продаж).
Нормализация данных — это общепринятая задача предобработки в 
машинном обучении. Многие алгоритмы предполагают, что все признаки 
находятся в единой шкале, как правило, от 0 до 1 или от -1 до 1. 
Существует множество способов нормализации значений признаков, 
чтобы масштабировать их к единому диапазону и использовать в различных 
моделях машинного обучения. В зависимости от используемой функции, их 
можно разделить на 2 большие группы: линейные и нелинейные. При 
нелинейной нормализации в расчетных соотношениях используются 
функции логистической сигмоиды или гиперболического тангенса. В 
линейной нормализации изменение переменных осуществляется 
пропорционально, по линейному закону.
На практике наиболее распространены следующие методы 
нормализации признаков:
• Минимакс – линейное преобразование данных в диапазоне [0..1], где 
минимальное и максимальное масштабируемые значения 
соответствуют 0 и 1 соответственно;
• Z-масштабирование данных на основе среднего значения и 
стандартного отклонения: производят деление разницы между 
переменной и средним значением на стандартное отклонение.
При масштабировании данных мы будем использовать одну из 
популярных библиотек машинного обучения Scikit-learn. Библиотека 
содержит пакет sklearn.preprocessing, который предоставляет широкие
возможности для нормализации данных. Следует отметить, что в целом
алгоритмы обучения выигрывают от стандартизации набора данных.

In [ ]:
3.2.1. Пример
Задача:
Прошкалируйте числовой признак в диапазоне между двумя значениями.
Решение:

In [ ]:
import numpy as np 
from sklearn import preprocessing
# Создаем признак
feature=np.array([[-500.5],[-100.1],[0],[100.1],[900.9]]) 
# Создаем шкалировщик
minmax_scale=preprocessing.MinMaxScaler(feature_range=(0,1))

scaled_feature=minmax_scale.fit_transform(feature)

scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

In [ ]:
3.2.2. Пример
Задача:
Преобразуйте признак, чтобы он имел среднее значение 0 и стандартное 
отклонение 1.
Решение:

In [ ]:
# Cоздаем признак
x=np.array([[-1000.1],[-200.1],[500.5],[600.6],[9000.9]])
# Cоздаем шкалировщик 
scaler=preprocessing.StandardScaler()
# Преобразовываем признак
standardized=scaler.fit_transform(x)
print(standardized)


print('Среднее: ',round(standardized.mean()))
print('Cтандартное отклонение:',standardized.std())

[[-0.76059041]
 [-0.54175168]
 [-0.35010367]
 [-0.32272147]
 [ 1.97516724]]
Среднее:  0
Cтандартное отклонение: 0.9999999999999999


In [ ]:
3.2.3. Пример
Задача:
Дан фрейм данных 
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
 'B':[103.02,107.26,110.35,114.23,114.68],
 'C':['big','small','big','small','small']})

Необходимо масштабировать его числовые столбцы.

Решение

In [ ]:
import pandas as pd 
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
dfTest = pd.DataFrame({
 'A':[14.00,90.20,90.95,96.27,91.21],
 'B':[103.02,107.26,110.35,114.23,114.68],
 'C':['big','small','big','small','small']})
dfTest[['A','B']]=scaler.fit_transform(dfTest[['A','B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

In [ ]:
url='https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
df = pd.read_csv(url,error_bad_lines=False, engine ='python')
df

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)


sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0                5.1             3.5              1.4             0.2   
1                4.9             3.0              1.4             0.2   
2                4.7             3.2              1.3             0.2   
3                4.6             3.1              1.5             0.2   
4                5.0             3.6              1.4             0.2   
..               ...             ...              ...             ...   
145              6.7             3.0              5.2             2.3   
146              6.3             2.5              5.0             1.9   
147              6.5             3.0              5.2             2.0   
148              6.2             3.4              5.4             2.3   
149              5.9             3.0              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [ ]:
import pandas as pd 
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
df['sepal_length_cm']=scaler.fit_transform(df[['sepal_length_cm']])
df['sepal_length_cm']

df

0      0.222222
1      0.166667
2      0.111111
3      0.083333
4      0.194444
         ...   
145    0.666667
146    0.555556
147    0.611111
148    0.527778
149    0.444444
Name: sepal_length_cm, Length: 150, dtype: float64

In [ ]:
import numpy as np 
from sklearn import preprocessing
scaler=preprocessing.StandardScaler()


df['sepal_width_cm']=scaler.fit_transform(df[['sepal_width_cm']])
df['sepal_width_cm']

0      1.032057
1     -0.124958
2      0.337848
3      0.106445
4      1.263460
         ...   
145   -0.124958
146   -1.281972
147   -0.124958
148    0.800654
149   -0.124958
Name: sepal_width_cm, Length: 150, dtype: float64